# Generated by Django 4.0.4 on 2022-11-09 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Fsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Тип Решения')),
            ],
        ),
        migrations.AddField(
            model_name='problem',
            name='correct_solution',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Решение задачи'),
        ),
        migrations.CreateModel(
            name='UsersSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('image_solution', models.ImageField(blank=True, default='logo.png', upload_to='users_solutions', verbose_name='Решение')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='Fsite.contest')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='Fsite.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='problem',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='Fsite.problemsolution'),
        ),
    ]
