# Generated by Django 4.0.4 on 2022-11-10 07:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fsite', '0002_problemsolution_problem_correct_solution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userssolution',
            name='mark',
            field=models.IntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(7)]),
        ),
        migrations.AddField(
            model_name='userssolution',
            name='text_solution',
            field=models.TextField(blank=True, null=True, verbose_name='РешениеТекс'),
        ),
        migrations.AlterField(
            model_name='userssolution',
            name='image_solution',
            field=models.ImageField(blank=True, null=True, upload_to='users_solutions', verbose_name='РешениеФото'),
        ),
    ]
