# Generated by Django 4.0.4 on 2022-11-11 19:38

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Fsite', '0006_userprofile_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='show_solution',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, null=True, verbose_name='Страна'),
        ),
    ]
