# Generated by Django 4.0.4 on 2022-11-11 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fsite', '0007_problem_show_solution_alter_userprofile_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='show_solution',
            field=models.BooleanField(default=False),
        ),
    ]
