# Generated by Django 4.0.4 on 2022-11-11 21:05

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Fsite', '0008_alter_problem_show_solution'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='hidden_content',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Текст полной статьи'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Краткое содержание'),
        ),
    ]
