# Generated by Django 4.0.4 on 2022-11-11 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fsite', '0010_rename_userssolution_usersolution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersolution',
            name='image_solution',
            field=models.ImageField(blank=True, null=True, upload_to='user_solutions', verbose_name='РешениеФото'),
        ),
    ]
