# Generated by Django 4.0.4 on 2022-11-18 13:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fsite', '0013_alter_userprofile_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='judges',
            field=models.ManyToManyField(blank=True, related_name='refereeing_contests', to=settings.AUTH_USER_MODEL),
        ),
    ]
