# Generated by Django 4.0.4 on 2022-11-28 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fsite', '0014_contest_judges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='source',
            field=models.CharField(default='Неизвестно', max_length=50, verbose_name='Источник'),
        ),
    ]
