# Generated by Django 4.0.4 on 2022-11-28 07:00

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Fsite', '0015_alter_problem_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50, unique=True, verbose_name='Предмет')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', tinymce.models.HTMLField(blank=True, verbose_name='Текст')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикация')),
                ('author', models.CharField(default='Admin', max_length=50, verbose_name='Автор')),
                ('source', models.CharField(default='Неизвестно', max_length=50, verbose_name='Источник')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material', to='Fsite.materialsubject')),
            ],
        ),
    ]
