# Generated by Django 4.0.4 on 2022-11-28 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Fsite', '0016_materialsubject_material'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materialsubject',
            old_name='subject',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='material',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='Fsite.materialsubject'),
        ),
    ]
