# Generated by Django 4.0.4 on 2022-11-28 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fsite', '0017_rename_subject_materialsubject_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='time_end',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='time_start',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
