# Generated by Django 4.0.4 on 2022-11-30 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fsite', '0018_material_time_end_material_time_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='answer',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ответ на задачу'),
        ),
    ]
