# Generated by Django 4.0.4 on 2022-12-01 04:14

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Fsite', '0020_problem_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', tinymce.models.HTMLField(blank=True, verbose_name='Текст задачи')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикация')),
                ('author', models.CharField(default='Admin', max_length=50, verbose_name='Автор')),
                ('source', models.CharField(default='Неизвестно', max_length=50, verbose_name='Источник')),
                ('answer', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ответ на задачу')),
                ('show_solution', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Вопрос по истории',
                'verbose_name_plural': 'Вопросы по истории',
                'ordering': ['time_update'],
            },
        ),
    ]
