# Generated by Django 4.0.4 on 2022-12-01 04:17

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Fsite', '0021_historyproblem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyproblem',
            name='answer',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ответ на вопрос'),
        ),
        migrations.AlterField(
            model_name='historyproblem',
            name='question',
            field=tinymce.models.HTMLField(verbose_name='Текст задачи'),
        ),
        migrations.AlterField(
            model_name='historyproblem',
            name='show_solution',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='historyproblem',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Время изменения'),
        ),
    ]
